# CI Pipeline for MeetSpot
name: CI Pipeline

on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main, feature ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test application import
      run: |
        python -c "import app; print('✅ App imports successfully')"

    - name: Check code style
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Docker build
      run: |
        if [ -f "Dockerfile" ]; then
          docker build -t meetspot:test .
        else
          echo "No Dockerfile found, skipping Docker build"
        fi
