name: Update Project Badges

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update README badges
        run: |
          echo "Updating project statistics badges..."
          REPO_NAME="${{ github.repository }}"
          echo "Repository: $REPO_NAME"
          echo "Badge update completed"

      - name: Check for changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, ready for commit"
          fi
